name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew app:build
    - name: Artifact naming
      run: |
        artifact="${{github.repository_owner}} ${{github.ref_name}}"
        artifact="${artifact//\//-}" # replace slashes
        echo "artifact=${artifact}" >> $GITHUB_ENV
    - name: Upload debug APK
      uses: actions/upload-artifact@v4
      with:
        name: "${{env.artifact}} debug_apk"
        path: app/build/outputs/apk/debug/*.apk
